name: Migrate DB and Deploy

on:
  push:
    branches: [main] # adjust if your prod branch is different

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install
        run: pnpm install --frozen-lockfile

      # Optional: prisma generate if your schema changed
      - name: Prisma generate
        run: pnpm prisma generate

      - name: Run Prisma migrations (prod)
        env:
          # Prisma automatically prefers DIRECT_URL for migrate if schema has it,
          # but we also pass both to be explicit.
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # pooled URL (not used by migrate)
          DIRECT_URL: ${{ secrets.DIRECT_URL }} # NON-pooled 5432 URL with sslmode=require
          # If your corp env injects custom CA:
          # NODE_EXTRA_CA_CERTS: ${{ secrets.NODE_EXTRA_CA_CERTS_PATH }}
        run: pnpm migrate:prod

  deploy:
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
